#!/bin/bash
# Linux Kniha kouzel, skript transakce
# Copyright (c) 2020 Singularis <singularis@volny.cz>
#
# Toto dílo je dílem svobodné kultury; můžete ho šířit a modifikovat pod
# podmínkami licence Creative Commons Attribution-ShareAlike 4.0 International
# vydané neziskovou organizací Creative Commons. Text licence je přiložený
# k tomuto projektu nebo ho můžete najít na webové adrese:
#
# https://creativecommons.org/licenses/by-sa/4.0/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Volání:
# transakce {-o|-z} {soubory}...

set -e

if test "$1" = "-o"
then
    shift
    for cil in "$@"
    do
        t="${cil}.transakce"
        if test -e "$cil"
        then
            cp -fpT -- "$cil" "$t"
        elif test -e "$t"
        then
            rm -f -- "$t"
        else
            true
        fi
    done

elif test "$1" = "-z"
then
    shift
    for cil in "$@"
    do
        t="${cil}.transakce"
        if test -e "$cil" -a -e "$t" && cmp -s -- "$cil" "$t"
        then
            mv -fT -- "$t" "$cil" && printf 'transakce: nezměněno (%s)\n' "$cil"
        else
            rm -f -- "$t" && printf 'transakce: změny potvrzeny (%s)\n' "$cil"
        fi
    done

elif test "$#" = 0 -o "$1" = "--help"
then
    printf 'Nápověda není implementována.\n'
    exit 0
else
    printf %s\\n "Chybné použití!" >&2
    exit 1
fi
