#cz
\# Linux Kniha kouzel, manuálová stránka
\#Copyright (c) 2019, 2020 Singularis <singularis@volny.cz>
\#
\#Toto dílo je dílem svobodné kultury; můžete ho šířit a modifikovat pod
\#podmínkami licence Creative Commons Attribution-ShareAlike 4.0 International
\#vydané neziskovou organizací Creative Commons. Text licence je přiložený
\#k tomuto projektu nebo ho můžete najít na webové adrese:
\#
\#https://creativecommons.org/licenses/by-sa/4.0/
\#
#en
\# Linux Kniha kouzel, the manual page
\#Copyright (c) 2019, 2020 Singularis <singularis@volny.cz>
\#
\#This work is work of free culture; you may modify and redistribute it
\#under the terms of Creative Commons Attribution-ShareAlike 4.0 International
\#License as issued by the non-profit organization Creative Commons.
\#The license text is attached to this project, or you may find it at
\#web address:
\#
\#https://creativecommons.org/licenses/by-sa/4.0/
\#
#0


#cz
.TH "LKK" 1 "8.\~ledna\~2020" "Linux: Kniha kouzel, v.p. 2.0"
.SH "JMÉNO"
lkk - spouští a\~vypisuje pomocné skripty Linuxu: Knihy kouzel
#en
.TH "LKK" 1 "January 8th 2020" "Linux: Kniha kouzel, v.p. 2.0"
.SH "NAME"
lkk - runs and executes helper scripts of Linux: Kniha kouzel


#cz
.SH "POUŽITÍ"
.SY lkk
[...] [\fB\-r\fR]
.I skript
[\fIparametry\fR]
.SY lkk
[...] \fB{\-e|\-f|\-p|\-t} \fIskript\fR
.SY lkk
[...] \fB\-\-funkce\fR
[\fInázevFunkce\fR]
.SY lkk
[...] \fB{\-l|\-\-seznam\-cest}
.YS
#en
.SH "SYNOPSIS"
.SY lkk
[...] [\fB\-r\fR]
.I script
[\fIparameters\fR]
.SY lkk
[...] \fB{\-e|\-f|\-p|\-t} \fIscript\fR
.SY lkk
[...] \fB\-\-funkce\fR
[\fIfunctionName\fR]
.SY lkk
[...] \fB{\-l|\-\-seznam\-cest}
.YS



#cz
.SH "POPIS"

Příkaz „lkk“ slouží k\~pohodlnému spouštění pomocných skriptů a\~funkcí
dodávaných s\~Linuxem: Knihou kouzel. Všechny dodávané skripty lze spustit
i\~přímo. Po instalaci se skripty nacházejí v\~adresáři
\fI/usr/share/lkk/skripty\fR.
.PP
Některé soubory v\~adresáři se skripty nejsou spustitelné.
Tyto soubory se nazývají „úryvky“ a\~lze s\~nimi pracovat stejně jako
se skripty, až na to, že není možné je přímo spouštět (jsou určeny
k\~vypsání příkazem „lkk \-p“).
#en
.SH "DESCRIPTION"
„lkk“ command is aimed for comfortable running of helper scripts and
helper functions shipped with Linux: Kniha kouzel. All shipped scripts
can be executed directly also. After installation scripts are located
at \fI/usr/share/lkk/skripty\fR directory.
.PP
Some files in the directory are not executable. Those files are called
„snippets“ and they may be treated the same as the scripts,
with exception that is is not possible to run them (they are aimed
to be printed by „lkk \-p“ command).


#cz
.SH "REŽIMY A VOLBY"
.SS "Režimy činnosti"
#en
.SH "MODES AND OPTIONS"
.SS "Modes"


#cz
.TP
\fB\-e \fIskript
Pokud skript existuje v\~uživatelově místním adresáři
(\(ti/.local/share/lkk/skripty), otevře ho ve výchozím editoru.
.RS
.PP
Pokud najde skript v\~jiném adresáři, vytvoří jeho kopii
v\~uživatelově adresáři a\~otevře ji ve výchozím editoru.
.PP
Pokud skript nenajde, vytvoří prázdný skript v\~uživatelově adresáři
a\~otevře ho ve výchozím editoru.
.PP
Doporučuji kombinovat s\~volbou \fB\-x\fR, aby případný
vytvořený skript byl spustitelný.
.RE
#en
.TP
\fB\-e \fIscript
If the script exists in user local directory
(\(ti/.local/share/lkk/skripty), it will be openned in the default editor.
.RS
.PP
If the script is found in another directory, a copy of it will be
created in the user local directory and openned in the default editor.
.PP
If the script is not found, a new empty script will be created in
the user default directory and openned in the default editor.

I recommend to combine this mode with \fB\-x\fR option to make
a new script executable.
.RE



#cz
.TP
\fB\-f \fIskript
Vypíše absolutní cestu k\~zadanému skriptu. Pokud skript neexistuje,
nic nevypíše a\~selže s\~návratovým kódem 1.
#en
.TP
\fB\-f \fIscript
Prints the absolute path to he given script. If the script does not exist,
nothing is printed and the command fails with return code 1.


#cz
.TP
\fB\-\-funkce \fR[\fInázevFunkce\fR]
Vypíše kód uvedené pomocné funkce (předponu „lkk_“ lze vynechat).
Neuvedete-li název funkce, vypíše kódy všech pomocných funkcí.
Pokud funkci nenajde, vypíše chybu a\~skončí s\~návratovým kódem 255.
.RS
.PP
Příkaz \fBlkk \-\-funkce\fR je synonymum pro \fBlkk -p pomocné-funkce\fR;
vypíše kód všech pomocných funkcí.
.RE
#en
.TP
\fB\-\-funkce \fR[\fIfunctionName\fR]
Prints the code of the named helper function (prefix „lkk_“ may be omitted).
If no function name is named, codes of all helper functions will be printed.
If the function is not found, an error message will be outputted
and the command fails with return code 255.
.RS
.PP
The command \fBlkk \-\-funkce\fR is a synonym for \fBlkk -p pomocné-funkce\fR;
it prints codes of all helper functions.
.RE



#cz
.TP
\fB\-l
Vypíše seznam všech dostupných skriptů (ve všech prohledávaných adresářích).
#en
.TP
\fB\-l
Prints a list of all available scripts (in all searched directories).



#cz
.TP
\fB\-p \fIskript
Vypíše obsah uvedeného skriptu nebo úryvku na standardní výstup.
Pokud skript neexistuje, nevypíše nic a\~selže s\~návratovým kódem 1.
#en
.TP
\fB\-p \fIscript
Prints the contents of the named script or snippet to the standard output.
If the script does not exist, nothing is printed and the command fails
with return code 1.


#cz
.TP
[\fB\-r\fR] \fIskript parametry
Výchozí režim příkazu „lkk“. Najde a\~spustí uvedený skript a\~předá mu zadané parametry.
#en
.TP
[\fB\-r\fR] \fIscript parameters
The default mode of „lkk“ command. Named script is found and executed
with given parameters.


#cz
.TP
\fB\-\-seznam\-cest
Vypíše seznam absolutních cest existujících adresářů,
ve kterých by byly vyhledávány skripty.
#en
.TP
\fB\-\-seznam\-cest
Prints the list of absolute paths of existing directories, where the scripts
would be searched for.



#cz
.TP
\fB-t \fIskript
Uspěje, pokud uvedený skript existuje. Pokud ne, selže s\~návratovým kódem 1.
Nic nevypisuje.
#en
.TP
\fB-t \fIscript
Succeeds, if the named script exists. If not, it fails with return code 1.
Nothing is printed.


#cz
.SS "Volby"
#en
.SS "Options"


#cz
.TP
\fB\-\-bash
V\~režimu \fB\-e\fR do nově vytvořeného skriptu přidá hlavičku
„#!/bin/bash“. Nemá vliv v\~případě, že se otevírá existující skript nebo
jeho kopie.
#en
.TP
\fB\-\-bash
In \fB\-e\fR mode the „#!/bin/bash“ header is added to the newly created
script. This option have no influence when an existing script is copied
or openned.



#cz
.TP
\fB\-s
Paranoidní režim. Ignoruje proměnnou prostředí LKKPATH a\~skripty vyhledává
výhradně v\~adresáři /usr/share/lkk/skripty. Ovlivňuje všechny režimy činnosti.
Pokud v\~režimu \fB\-e\fR existuje uživatelův lokální skript i\~skript systémový,
uživatelův lokální skript bude před otevřením přepsán kopií systémového.
#en
.TP
\fB\-s
Paranoid mode. Environment variable LKKPATH is ignored and scripts are
searched for only in /usr/share/lkk/skripty directory.
This have influence to all modes.
If there is both user-local and system-wide script in \fB\-e\fR mode,
the user-one will be overwritten by copy of the system one.


#cz
.TP
\fB\-x
Všechny režimy činnosti kromě \fB\-e\fR:
Ignorovat skripty, které nejsou spustitelné. Příkaz bude zohledňovat pouze
skripty s\~nastaveným právem spouštění. Doporučuji nekombinovat s\~režimem
\fB\-\-funkce\fR.
.RS
.PP
Režim činnosti \fB\-e\fR: Pokud vytvoří nový uživatelův lokální skript,
nastaví mu právo spouštění. To neplatí, pokud bude vytvořen jako kopie
skriptu nalezeného jinde.
.RE
#en
.TP
\fB\-x
All modes except \fB\-e\fR:
Ignore non-executable scripts. Only executable scripts will be considered.
I recommend not to combine this with \fB\-\-funkce\fR mode.
.RS
.PP
Mode \fB\-e\fR: If a new user-local script is created, an executable right
is set on it. This is not true when the script si created as a copy of
script from otherwhere.
.RE


#cz
.SH "POMOCNÉ SKRIPTY A\~FUNKCE"
Tato sekce manuálové stránky poskytuje popis některých konkrétních
pomocných skriptů a\~funkcí dodávaných s\~Linuxem: Knihou kouzel (ne nutně všech).
#en
.SH "HELPER SCRIPTS AND FUNCTIONS"
Particular scripts and functions are described only in the czech version
of this manual page.


#cz
.SS "lkk diskstat (skript, kapitola Diskové oddíly)"
\fBlkk diskstat \fR[\fI/dev/zařízení\fR]...
.PP
Vypisuje ve formátu TSV aktuální hodnoty počítadel přečtených a\~zapsaných bajtů
pro zadaná zařízení. První sloupec obsahuje cestu zařízení, jak byla zadána,
druhý počet bajtů přečtených od připojení zařízení (resp. od startu systému)
a\~třetí počet bajtů zapsaných za stejné období.
Bez parametrů vypíše všechny dostupné nenulové statistiky.
.SS "lkk perl (skript, kapitola Perl: základy)"
\fBlkk perl \fR[\fIparametry Perlu\fR] \fIskript\fR [\fIparametry skriptu\fR]
.PP
Spustí zadaný skript v\~Perlu s\~nastaveními potřebnými pro kapitolu
Linuxu: Knihy kouzel o\~Perlu. (Mezi ně patří i\~připojení pomocného modulu
Linuxu: Knihy kouzel.)
.SS "lkk procesy (skript, kapitola Správa procesů)"
Vypíše přehled PID všech procesů ve strojově zpracovatelném formátu TSV,
kde oddělovačem je dvojtečka „:“. První sloupec obsahuje PID procesu,
každý další sloupec pak obsahuje PPID procesu z předchozího sloupce,
tím pádem každá řádka obsahuje sekvenci PID od konkrétního procesu až po
démona s\~PID 1 nebo 2.
.PP
Poznámka: V\~této verzi vyžaduje nainstalovaný balíček „gawk“.
.SS "lkk retence (skript, kapitola AWK)"
Načte celý obsah standardního vstupu do paměti a\~teprve po jeho ukončení
ho beze změny vypíše na standardní výstup.
.PP
Poznámka: V\~této verzi vyžaduje nainstalovaný balíček „gawk“.
.SS "lkk_barvapronh (funkce, kapitola Terminál)"
\fBlkk_barvapronh \fIčíslo
.PP
Pro 0 neudělá nic. Pro číslo 1 nastaví tučné červené písmo, pro číslo vyšší
než 1 nastaví tučné zelené písmo.
.SS "lkk_bezp_set (funkce, kapitola Terminál)"
\fBlkk_bezp_set {setaf|setab} \fIčíslobarvy\fR...
.PP
Z\~uvedených barev vybere a\~nastaví tu první, kterou aktuální terminál
podporuje (čísla musejí být v\~rozsahu 0 až 255). Pokud terminál nepodporuje
žádné barvy, neudělá nic.
.SS "lkk_pstput (funkce, kapitola Terminál)"
\fBlkk_pstput {parametry}
.PP
Přijímá stejné parametry jako příkaz „tput“; před jeho provedením ovšem vypíše
„\\[“ a\~po jeho provedení „\\]“. Smyslem je pohodlnější integrace příkazu
tput do výzev PS1 a\~PS2.

#cz
.SH "PROMÉNNÉ PROSTŘEDÍ"
#en
.SH "ENVIRONMENT"

#cz
.TP
\fBEDITOR
Určuje editor, který se spustí v\~režimu \fB\-e\fR. Je-li prázdná
nebo nedefinovaná, použije se „sensible-editor“.
#en
.TP
\fBEDITOR
Selects the editor to use in \fB\-e\fR mode. If empty or undefined,
„sensible-editor“ will be used.


#cz
.TP
\fBLKKPATH
Dvojtečkou oddělený seznam cest adresářů, kde budou vyhledávány skripty.
Je-li prázdná nebo nedefinovaná, použije se
„${HOME}/.local/share/lkk/skripty:/usr/share/lkk/skripty“.
Adresáře se prohledávají zleva doprava a\~neexistující adresáře jsou
tiše ignorovány.
#en
.TP
\fBLKKPATH
Semicolon-separated list of directory paths to search for scripts.
If empty of undefined,
„${HOME}/.local/share/lkk/skripty:/usr/share/lkk/skripty“ will be used.
Directories are searched from the left to the right and non-existent
directories are silently ignored.


#cz
.SH "HLÁŠENÍ CHYB"
Chyby prosím hlaste jako issue na GitHubu:
.UR https://github.com/singularis-mzf/linux-spellbook
Repozitář na GitHubu
.UE , nebo na e-mailovou adresu:
.PP
.RS
Singularis <singularis@volny.cz>
.RE
#en
.SH "BUG REPORTING"
Please notify me of bugs using GitHub issues:
.UR https://github.com/singularis-mzf/linux-spellbook
GitHub repository
.UE or e-mail address:
.PP
.RS
Singularis <singularis@volny.cz>
.RE


#cz
.SH "LICENCE"
Všechny části balíčku „lkk“ (zejména samotné skripty) podléhají licenci
Creative Commons Attribution-ShareAlike 4.0 International.
Detailní informace včetně údajů o\~autorství najdete v\~souboru
\fI/usr/share/doc/lkk/copyright\fR.
.PP
Spouštěč „lkk“ je možno používat a\~šířit také za podmínek
GNU General Public License verze 2.
.PP
Modul Perlu „LinuxKnihaKouzel.pm“ je možno používat a\~šířit bez dalších
podmínek podle licence Creative Commons CC0 1.0.
#en
.SH "LICENCE"
All parts of „lkk“ package (especially the scripts) may be modified
and redistributed under the terms of Creative Commons
Attribution-ShareAlike 4.0 International License.
You can found detail informations including authorship-info in the file
\fI/usr/share/doc/lkk/copyright\fR.
.PP
The „lkk“ launcher is available also under the terms of
GNU General Public License version 2.
.PP
The Perl module „LinuxKnihaKouzel.pm“ is freely available with no other
conditions under Creative Commons CC0 1.0 License.
#0
\".SH "SEE ALSO"
\".SH "VIZ TAKÉ"
